const colors = {
  primary: "#6d48e5",
  onPrimary: "#FFFFFF",
  onPrimaryContainer: "#BEDBED",
  primaryShade: "#ece7fe",
  primaryShade2: "#f4f1fe",
  accent: "#000000",
  onAccent: "#FFFFFF",
  accentContainer: "#343434",
  onAccentContainer: "#FFFFFF",
  surface: "#FAF7FF",
  onSurface: "#474747",
  onSurfaceContainer: "#333",
  disabled: "#DCDCDC",
  onDisabled: "#696969",
  background: "#FFFFFF",
  onBackground: "black",
  error: "#FF77B4",
  onError: "white",
  errorContainer: "#FF77B4",
  onErrorContainer: "#000000",
  divider: "#DCDCDC",
  border: "#DCDCDC",
  text: "black",
  text2: "#6D759D",
  text3: "#9198B3",
  text4: "#b3b3b3",
  white: "#FFFFFF",
  black: "#000000",
  transparent: "transparent",
};

export default colors;
